### ISSUE TITLE
Cardano wallets sanity check automation

### ISSUE THREAD

**Issue by kukkok3** [input-output-hk/catalyst-core#626]
## Description

Before each fund we need to sanity check that external wallets are still submitting the right registration transaction and generating the right qr code. Instead of doing this manually we can create a testsuite to automate it. Using playwright do ->

- Create a new wallet in the wallet UI (or have a bunch of pre generated test wallets stored in the repo)
- Get at least 500 test ada from the faucet (or check that the pregenerated wallets still have enough funds)
- Register for voting on the external wallet UI
- Check the registration metadata shown by the wallet UI
- Check the registration transaction can be found in https://api.dev.projectcatalyst.io/api/v1/registration/delegations/{voting-key}
- Check the qr code generated by the wallet is correct using https://github.com/input-output-hk/chain-wallet-libs/ to estract the voting key

The test should be build in such a way that is possible to run it locally using a mainnet wallet. **Do not expose any mainnet wallet info/keys/qr**

## Tasks

- [x] https://github.com/input-output-hk/catalyst-core/issues/654
- [x] https://github.com/input-output-hk/catalyst-core/issues/677
- [ ] https://github.com/input-output-hk/catalyst-core/issues/678
- [ ] https://github.com/input-output-hk/catalyst-core/issues/679

## Docs

List of supported wallets and a guide on how to register can be found at https://docs.projectcatalyst.io/about-project-catalyst/what-is-project-catalyst
How to register a preprod wallet
https://docs.projectcatalyst.io/project-catalyst-testnet/testnet-voting-events/testnet-user-guide/register-wallet 
Registration metadata format can be found at https://cips.cardano.org/cips/cip36/#registrationmetadataformat

**Comment by vasapornchaiyakul** [comment]
@stevenj @kukkok3 I cannot assign myself to this ticket... maybe I don't have the permission?
