### ISSUE TITLE
🏛️ [EPIC] : Add Artifact records to cardano blockchain during fund 12+ cycles.

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-core#676]
**Summary**

We need to create and record records on the blockchain to help audit the various artefacts we produce during a fund, starting with F12.

**JIRA Epic**

https://input-output.atlassian.net/browse/NPG-????

**Description**

The main artifacts we need to capture are:

* All the event start artifacts:
  * Block 0
  * Snapshot
  * Final proposals lists/reviews/etc
  * Other stuff?
* Running audit entries
  * 1 record per blockchain archive (1 per hour) during F12.
* Final Artifacts
  *  Results
  * Anything else?

The metadata on chain needs to capture:

* name of the fund
* name of the artifact
* hash of the artifact
* link to the artifact

We can store this as an array so we can put multiple entries in a single transaction (as required).

**Todo**

- [ ] Define the authoritative list of Artifacts to save
- [ ] Define the exact metadata record to save
- [ ] Create a tool to allow us to automate the creation of these records and post them on-chain.
- [ ] Integrate the tool with Artifact generation and Jormungandr blockchain snapshots.
- [ ] Document what the community should look for on-chain if they want to independently validate these artifacts.
- [ ] Create a public catalyst-artifacts repo to hold the public artifacts we otherwise would have stored in the private catalyst-artifacts repo so we can link to it from metadata.
- [ ] test it all works as expected during dry-runs using the pre-prod network.
- [ ] other stuff?

**Comment by kukkok3** [comment]
Should we just share the vitss db instead of proposals lists/reviews/etc?

**Comment by stevenj** [comment]
Suggested Metadata:
Use CIP-20

### Example for multiple messages/comments/memos:
``` json
{
  "674":
         {
           "msg":
                  [
                    "Catalyst Audit Data",
                    "fund-name: fund 1234",
                    "artifact: Fund Parameters",
                    "hash: 0x1234...abcd",
                    "link: www.somewhere.io/something/something/FundParameters.zip"
                  ]
         }
}
```
